project:
  type: website

website:
  title: "Meiyi Chen"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: Education
      - href: project.qmd
        text: Work Experience
  page-footer: 
    right: "&copy, 2024,Meiyi Chen"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto



