project:
  type: website

website:
  title: "Meiyi Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Bio
      - href: project.qmd
        text: Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto



